name: json_translator
description: Json Translator

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^3.12.0
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+2
  file_picker: ^5.0.1
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  logger: ^1.1.0
  file_icon: ^1.0.0
  translator: ^0.1.7
  loader_overlay: ^2.0.10
  window_manager: ^0.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.1.0+1


  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

